# Use custom format
format = """
[ @](bold green) $directory| $username on $hostname
[](bold green) $package | $git_status$git_branch
[ >>](bold green) """

right_format = """
[───>](bold green)$username$hostname
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set "foo" as custom color palette
palette = "foo"

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = "21"
# Define new color
mustard = "#af8700"

[directory]
truncation_symbol = "…/"

[git_branch]
symbol = 'ø '
truncation_symbol = ''

[git_status]
ahead = '[++ ${count}](green)'
behind = '[-- ${count}](red)'
diverged = '[++ ${ahead_count} | -- ${behind_count}](red)'
up_to_date = '[HEAD == Origin](aqua)'
untracked = '[??? Untracked](green)'
modified = '[!!! Modified](red) '
staged = '[++\($count\)](green)'

[hostname]
ssh_only = false
format = '[$hostname](fg:#ff6f61)'
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true
